# Generated by Django 2.2.10 on 2020-05-01 00:06

from django.db import migrations, models
import jsonfield.fields


class Migration(migrations.Migration):

    dependencies = [
        ('course_planner_api', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='courseitem',
            name='semester_placement',
        ),
        migrations.RemoveField(
            model_name='courseitem',
            name='year_placement',
        ),
        migrations.AddField(
            model_name='courseitem',
            name='term_placement',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='study_terms',
            field=jsonfield.fields.JSONField(blank=True, null=True),
        ),
    ]
