# Generated by Django 2.2.10 on 2020-05-03 00:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course_planner_api', '0002_auto_20200501_0006'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='courses',
            field=models.ManyToManyField(to='course_planner_api.CourseItem'),
        ),
    ]
