# Generated by Django 2.2.10 on 2020-05-03 01:08

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('course_planner_api', '0003_userprofile_courses'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='courseitem',
            name='term_placement',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='courses',
        ),
        migrations.CreateModel(
            name='SemesterGroup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('semester', models.CharField(max_length=10)),
                ('user_profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='courseitem',
            name='semester_placement',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='course_planner_api.SemesterGroup'),
        ),
    ]
