# Generated by Django 2.2.10 on 2020-05-03 20:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course_planner_api', '0004_auto_20200503_0108'),
    ]

    operations = [
        migrations.AlterField(
            model_name='semestergroup',
            name='semester',
            field=models.CharField(max_length=50),
        ),
    ]
