# Generated by Django 2.2.10 on 2020-05-04 03:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course_planner_api', '0005_auto_20200503_2042'),
    ]

    operations = [
        migrations.AlterField(
            model_name='semestergroup',
            name='semester',
            field=models.CharField(max_length=12),
        ),
    ]
